apiVersion: v1
kind: ImageStream
metadata:
    name: drupal
spec:
    tags:
    - from:
          kind: DockerImage
          name: docker-registry.default.svc:5000/govil/drupal
      name: latest
      importPolicy:
          scheduled: true
