apiVersion: v1
kind: ImageStream
metadata:
    name: php72
spec:
    tags:
    - from:
          kind: DockerImage
          name: docker.io/dimssss/s2i-nginx-php72
      name: latest
      importPolicy:
          scheduled: true
